[package]
name = "kivinge"
version = "0.1.0"
edition = "2021"

[lib]
name = "kivinge"

[dependencies]
base64 = "0.22.1"
clap = "4.5.4"
crossterm = "0.27.0"
pkce = "0.2.0"
qrcode = { version = "0.14.0", default-features = false }
rand = "0.8.5"
ratatui = "0.26.2"
reqwest = { version = "0.12.4", features = ["blocking", "json", "gzip"] }
rust_decimal = "1.35.0"
serde = { version = "1.0.202", features = ["derive"] }
serde_json = "1.0.117"
sha1 = "0.10.6"
sha256 = { version = "1.5.0", default-features = false }
thiserror = "1.0.61"
time = { version = "0.3.36", features = ["serde"] }
